#!/bin/bash
# Claude Code Adapter — Clean Script
# Removes all files generated by the Claude Code adapter
#
# Usage: bash adapters/claude/clean.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

source "$PROJECT_ROOT/.ai/scripts/_lib.sh"

echo -e "${BLUE}=== Claude Code Adapter Clean ===${NC}"
echo ""

REMOVED=0

# Remove .claude/ directory
if [ -d "$PROJECT_ROOT/.claude" ]; then
    rm -rf "$PROJECT_ROOT/.claude"
    echo -e "${GREEN}✓${NC} Removed .claude/"
    REMOVED=$((REMOVED + 1))
fi

# Remove CLAUDE.md
if [ -f "$PROJECT_ROOT/CLAUDE.md" ]; then
    rm "$PROJECT_ROOT/CLAUDE.md"
    echo -e "${GREEN}✓${NC} Removed CLAUDE.md"
    REMOVED=$((REMOVED + 1))
fi

echo ""
if [ $REMOVED -eq 0 ]; then
    echo -e "${YELLOW}Nothing to clean — Claude Code adapter output not found.${NC}"
else
    echo -e "${GREEN}=== Claude Code adapter output removed ($REMOVED items) ===${NC}"
fi
