#!/bin/bash
# Aider Adapter — Clean Script
# Removes all files generated by the Aider adapter
#
# Usage: bash adapters/aider/clean.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

source "$PROJECT_ROOT/.ai/scripts/_lib.sh"

echo -e "${BLUE}=== Aider Adapter Clean ===${NC}"
echo ""

REMOVED=0

# Remove .aider.conf.yml
if [ -f "$PROJECT_ROOT/.aider.conf.yml" ]; then
    rm "$PROJECT_ROOT/.aider.conf.yml"
    echo -e "${GREEN}✓${NC} Removed .aider.conf.yml"
    REMOVED=$((REMOVED + 1))
fi

# Remove CONVENTIONS.md (generated by Aider adapter)
if [ -f "$PROJECT_ROOT/CONVENTIONS.md" ]; then
    # Only remove if it's auto-generated (check for adapter comment)
    if head -5 "$PROJECT_ROOT/CONVENTIONS.md" | grep -q "Auto-generated.*Aider adapter"; then
        rm "$PROJECT_ROOT/CONVENTIONS.md"
        echo -e "${GREEN}✓${NC} Removed CONVENTIONS.md (auto-generated)"
        REMOVED=$((REMOVED + 1))
    else
        echo -e "${YELLOW}⚠${NC} Skipping CONVENTIONS.md — not auto-generated (may be manually maintained)"
    fi
fi

echo ""
if [ $REMOVED -eq 0 ]; then
    echo -e "${YELLOW}Nothing to clean — Aider adapter output not found.${NC}"
else
    echo -e "${GREEN}=== Aider adapter output removed ($REMOVED items) ===${NC}"
fi
